# Generated by Django 5.2.6 on 2025-09-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_customuser_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='liked_songs',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('listener', 'Listener'), ('creator', 'Creator')], default='listener', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
