# Generated by Django 5.2.6 on 2025-09-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_song_unique_together_alter_creator_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='song',
            name='unique_song_author',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration_in_seconds',
        ),
        migrations.AddField(
            model_name='customuser',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='music.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='author_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='theme_image',
            field=models.ImageField(blank=True, null=True, upload_to='song_images/'),
        ),
    ]
